# A minimal, versionless conda env file, for building 
# a version-pinned version of the file
name: sez
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - jupyter
  - jupyterlab
  - scipy
  - nltk
  - networkx
  - scikit-learn
  - pip
  - nomkl # Fixes https://github.com/dmlc/xgboost/issues/1715
  - pip:
    - spacy>=3
    - metapack
    - metapack-build
    - metapack-github
    - metapack-jupyter
    - metapack-wp
    - nameparser
    - python-slugify
    - requests
    - rowgenerators
    - seaborn
    - tqdm
    - xlrd
